7_file: 7_10_april_manage.cpp
	/usr/local/bin/g++-4.8 --std=c++11 -o 7_file 7_10_april_manage.cpp -I.

6_file: 6_8_april.cpp
	/usr/local/bin/g++-4.8 --std=c++11 -o 6_file 6_8_april.cpp -I.

non_poly: 1_non_polymorphic.cpp
	/usr/local/bin/g++-4.8 --std=c++11 -o non_poly 1_non_polymorphic.cpp  -I.

virtual: 2_polymorphic_base.cpp
	/usr/local/bin/g++-4.8 --std=c++11 -o virtual 2_polymorphic_base.cpp -I.

overload: 3_function_overload_overridde.cpp
	/usr/local/bin/g++-4.8 --std=c++11 -o overload 3_function_overload_overridde.cpp -I.
	
4_file: 4_1_april.cpp
	/usr/local/bin/g++-4.8 --std=c++11 -o 4_file 4_1_april.cpp -I.

5_file: 5_3_april.cpp
	/usr/local/bin/g++-4.8 --std=c++11 -o 5_file 5_3_april.cpp -I.
